name: "criticwave-action"
description: "Analyzes PR & review it using Gemini API"
author: "Devi Prakash"

inputs:
  github-token:
    description: "GitHub token to post comments"
    required: true
  gemini-api-key:
    description: "Your Gemini API key"
    required: true
  pr-style-guide:
    description: "Style guide prompt for the review"
    required: true
  model:
    description: "Model to use for review API"
    required: false
    default: "gemini-2.0-flash"

runs:
  using: "node20"
  main: "dist/index.js"
