name: Build and release on master push

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }} # PAT with repo access

      - name: Setup Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Commit dist folder if changed
        run: |
          git config user.name "dprakash2101"
          git config user.email "${{ secrets.EMAIL }}"
          git add dist
          if ! git diff --cached --quiet; then
            git commit -m "Build: update dist folder on main push"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes in dist folder"
